/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopproject;

import javax.swing.JFrame;
import static oopproject.Oopproject.height;
import static oopproject.Oopproject.width;

/**
 *
 * @author owner
 */
public class high_score extends javax.swing.JFrame {

    /**
     * Creates new form high_score
     */
    public high_score() {
        player playerr = new player();
        initComponents();
        lable1score.setVisible(false);
        lable2score.setVisible(false);
        lable3score.setVisible(false);
        lable2name.setVisible(false);
        lable3name.setVisible(false);
        lable1name.setVisible(false);
        playerr.highest();
        if (player.players.isEmpty()){
             lable1name.setVisible(true);
        lable1name.setText("no player");
         lable1score.setVisible(true);
        lable3name.setText("0");}
        else{
            for (int i = 0; i < player.players.size(); i++) {
                if(null != player.players.get(i).getPlayer_name()){
                if(i == 1){
                   lable1name.setVisible(true);
                  lable1name.setText(player.players.get(i).getPlayer_name());
                 lable1score.setVisible(true);
                 lable1score.setText(String.valueOf(player.players.get(i).getScore()));
                }
                else if (i == 2){
                  lable2name.setVisible(true);
                  lable2name.setText(player.players.get(i).getPlayer_name());
                 lable2score.setVisible(true);
                 lable2score.setText(String.valueOf(player.players.get(i).getScore()));
                }
                 else if (i == 3){
                  lable3name.setVisible(true);
                  lable3name.setText(player.players.get(i).getPlayer_name());
                 lable3score.setVisible(true);
                 lable3score.setText(String.valueOf(player.players.get(i).getScore()));
                }
                        
                }
                
            }
         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lable1name = new javax.swing.JLabel();
        lable3score = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lable2name = new javax.swing.JLabel();
        lable2score = new javax.swing.JLabel();
        lable1score = new javax.swing.JLabel();
        lable3name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 800, 600));
        setLocation(new java.awt.Point(300, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                  Highest  Score");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 620, 64));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 170, 40));

        lable1name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable1name.setForeground(new java.awt.Color(255, 255, 255));
        lable1name.setText("label1name");
        getContentPane().add(lable1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 156, 104));

        lable3score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable3score.setForeground(new java.awt.Color(255, 255, 255));
        lable3score.setText("label3score");
        getContentPane().add(lable3score, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 156, 150));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        lable2name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable2name.setForeground(new java.awt.Color(255, 255, 255));
        lable2name.setText("label2name");
        getContentPane().add(lable2name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 156, 104));

        lable2score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable2score.setForeground(new java.awt.Color(255, 255, 255));
        lable2score.setText("label2score");
        getContentPane().add(lable2score, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 156, 104));

        lable1score.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable1score.setForeground(new java.awt.Color(255, 255, 255));
        lable1score.setText("label1score");
        getContentPane().add(lable1score, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 156, 104));

        lable3name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lable3name.setForeground(new java.awt.Color(255, 255, 255));
        lable3name.setText("label3name");
        getContentPane().add(lable3name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 156, 104));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/score.jpg"))); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -80, 1020, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       first_form_jframe main = new first_form_jframe();
     
        main.setSize(width,height);
        main.setLocation(300, 300);
        main.setResizable(false);
        main.setVisible(true);
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lable1name;
    private javax.swing.JLabel lable1score;
    private javax.swing.JLabel lable2name;
    private javax.swing.JLabel lable2score;
    private javax.swing.JLabel lable3name;
    private javax.swing.JLabel lable3score;
    // End of variables declaration//GEN-END:variables
}
